/*
 *      Copyright 2016-2017 Riccardo Musso
 *
 *      Licensed under the Apache License, Version 2.0 (the "License");
 *      you may not use this file except in compliance with the License.
 *      You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *      Unless required by applicable law or agreed to in writing, software
 *      distributed under the License is distributed on an "AS IS" BASIS,
 *      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *      See the License for the specific language governing permissions and
 *      limitations under the License.
 *
 *      File utils/unicode/chars_3_2.inc
 *
*/

{ 0xe1b4b4, 0xcab0 }, { 0xe1b4b6, 0xcab2 }, { 0xe1b4b8, 0xcba1 }, { 0xe1b4bf, 0xcab3 },
{ 0xe1b582, 0xcab7 }, { 0xe1ba9e, 0xc39f }, { 0xe2b1a2, 0xc9ab }, { 0xe2b1a4, 0xc9bd },
{ 0xe2b1ad, 0xc991 }, { 0xe2b1ae, 0xc9b1 }, { 0xe2b1af, 0xc990 }, { 0xe2b1b0, 0xc992 },
{ 0xe2b1be, 0xc8bf }, { 0xe2b1bf, 0xc980 }, { 0xea9e8d, 0xc9a5 },
