/*
 *      Copyright 2016-2017 Riccardo Musso
 *
 *      Licensed under the Apache License, Version 2.0 (the "License");
 *      you may not use this file except in compliance with the License.
 *      You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *      Unless required by applicable law or agreed to in writing, software
 *      distributed under the License is distributed on an "AS IS" BASIS,
 *      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *      See the License for the specific language governing permissions and
 *      limitations under the License.
 *
 *      File utils/unicode/chars_4_3.inc
 *
*/

{ 0xf09f8490, 0xe2929c }, { 0xf09f8491, 0xe2929d }, { 0xf09f8492, 0xe2929e }, { 0xf09f8493, 0xe2929f },
{ 0xf09f8494, 0xe292a0 }, { 0xf09f8495, 0xe292a1 }, { 0xf09f8496, 0xe292a2 }, { 0xf09f8497, 0xe292a3 },
{ 0xf09f8498, 0xe292a4 }, { 0xf09f8499, 0xe292a5 }, { 0xf09f849a, 0xe292a6 }, { 0xf09f849b, 0xe292a7 },
{ 0xf09f849c, 0xe292a8 }, { 0xf09f849d, 0xe292a9 }, { 0xf09f849e, 0xe292aa }, { 0xf09f849f, 0xe292ab },
{ 0xf09f84a0, 0xe292ac }, { 0xf09f84a1, 0xe292ad }, { 0xf09f84a2, 0xe292ae }, { 0xf09f84a3, 0xe292af },
{ 0xf09f84a4, 0xe292b0 }, { 0xf09f84a5, 0xe292b1 }, { 0xf09f84a6, 0xe292b2 }, { 0xf09f84a7, 0xe292b3 },
{ 0xf09f84a8, 0xe292b4 }, { 0xf09f84a9, 0xe292b5 },
